import {Type} from "typebox";import {Check} from "typebox/value";
import {assembleObjectDeleteReceipt,emptyObjectDeleteData,objectDeleteFailure,objectDeleteArgv,objectDeletePrefix,presentObjectDeleteReceipt,validObjectDeleteOperands,validObjectDeleteText as safeBranchDeleteText,type ObjectDeleteAction,type ObjectDeleteReceipt} from "../operations/object-delete-receipt";
const obj=(p:Record<string,any>)=>Type.Object(p,{additionalProperties:false}),enm=(v:string[])=>Type.Union(v.map(x=>Type.Literal(x))),nil=(s:any)=>Type.Union([s,Type.Null()]),uint=(n=Number.MAX_SAFE_INTEGER)=>Type.Integer({minimum:0,maximum:n}),text=Type.String({minLength:1,maxLength:4096});
const attempt=obj({state:enm(["not-attempted","not-started","started","unknown"]),terminal:enm(["not-observed","observed"]),exitCode:nil(uint(2147483647)),aborted:Type.Boolean(),timedOut:Type.Boolean()}),capture=obj({stdoutBytes:uint(),stderrBytes:uint(),stdoutRetainedBytes:uint(65536),stderrRetainedBytes:uint(16384),truncated:Type.Boolean(),complete:Type.Boolean(),validUtf8:Type.Boolean()});
function schema<A extends ObjectDeleteAction>(action:A){const request=obj({operands:Type.Array(text,{minItems:1,maxItems:action==="shelveset-delete"?1:256}),repository:action==="shelveset-delete"?Type.Null():nil(text),workdir:text,preflight:Type.Boolean(),format:enm(["text","json"])}),data={requested:nil(request),intendedArgv:Type.Array(Type.String({minLength:1,maxLength:8192}),{minItems:2,maxItems:259}),attempt,capture:nil(capture),observedDeletedObjects:Type.Null(),observedRepositoryIdentity:Type.Null(),scope:Type.Literal("requested-only"),rollback:Type.Literal("not-proven")},header={schemaVersion:Type.Literal(1),action:Type.Literal(action),provenance:obj({source:Type.Literal("plastic"),producer:Type.Literal("@aefree/pi-plastic"),contentTrust:Type.Literal("external")}),completeness:obj({capture:enm(["complete","incomplete","unknown"]),projection:Type.Literal(true)})},error=obj({code:enm(["invalid_request","launch_failed","aborted","uncertain","producer_failed"]),message:Type.String({minLength:1,maxLength:256})});return Type.Unsafe<ObjectDeleteReceipt & {action:A;data:{requested:(ObjectDeleteReceipt["data"]["requested"] & {repository:A extends "shelveset-delete"?null:string|null})|null}}>(Type.Union([obj({...header,ok:Type.Literal(true),outcome:Type.Literal("preflight"),data:obj({...data,effect:Type.Literal("not-attempted")})}),obj({...header,ok:Type.Literal(true),outcome:Type.Literal("command-completed"),data:obj({...data,effect:Type.Literal("not-proven")})}),obj({...header,ok:Type.Literal(false),outcome:Type.Literal("failed"),data:obj({...data,effect:Type.Literal("not-attempted")}),error}),obj({...header,ok:Type.Literal(false),outcome:Type.Literal("uncertain"),data:obj({...data,effect:Type.Literal("uncertain")}),error})]));}
export const shelvesetDeleteOutputSchema=schema("shelveset-delete"),codeReviewDeleteOutputSchema=schema("code-review-delete");
export function validateObjectDeleteOutput(v:unknown):v is ObjectDeleteReceipt{if(!v||typeof v!=="object")return false;const dto=v as ObjectDeleteReceipt;if(!["shelveset-delete","code-review-delete"].includes(dto.action)||!Check(dto.action==="shelveset-delete"?shelvesetDeleteOutputSchema:codeReviewDeleteOutputSchema,v)||Buffer.byteLength(JSON.stringify(v),"utf8")>131072)return false;const d=dto.data,r=d.requested,a=d.attempt,c=d.capture;
 if(r===null){if(JSON.stringify(d.intendedArgv)!==JSON.stringify(objectDeletePrefix(dto.action))||c||a.terminal!=="not-observed"||a.exitCode!==null||a.aborted||a.timedOut||!["not-attempted","unknown"].includes(a.state))return false;}else{if(!validObjectDeleteOperands(dto.action,r.operands)||!safeBranchDeleteText(r.workdir)||r.repository!==null&&!safeBranchDeleteText(r.repository)||Buffer.byteLength(JSON.stringify(r),"utf8")>32768||JSON.stringify(d.intendedArgv)!==JSON.stringify(objectDeleteArgv(dto.action,r)))return false;}
 if(a.exitCode!==null&&a.terminal!=="observed"||["not-attempted","not-started"].includes(a.state)&&(a.terminal!=="not-observed"||a.exitCode!==null)||a.state==="not-attempted"&&a.timedOut)return false;
 if(c){if(!r||c.stdoutRetainedBytes>c.stdoutBytes||c.stderrRetainedBytes>c.stderrBytes)return false;if(c.complete&&(!c.validUtf8||c.truncated||c.stdoutBytes!==c.stdoutRetainedBytes||c.stderrBytes!==c.stderrRetainedBytes||a.state!=="started"||a.terminal!=="observed"||a.exitCode===null||a.aborted||a.timedOut))return false;if(a.state==="not-attempted"&&(!a.aborted||c.stdoutBytes||c.stderrBytes||c.validUtf8||c.complete))return false;}
 if(dto.completeness.capture!==(c?c.complete?"complete":"incomplete":"unknown"))return false;
 if(r?.preflight===true&&(!dto.ok||dto.outcome!=="preflight"||c||a.state!=="not-attempted"||a.terminal!=="not-observed"||a.exitCode!==null||a.aborted||a.timedOut))return false;
 if(dto.ok&&dto.outcome==="preflight"&&!r?.preflight)return false;if(dto.ok&&dto.outcome==="command-completed"&&(!r||r.preflight||!c?.complete||a.state!=="started"||a.exitCode!==0))return false;
 if(!dto.ok){if(!safeBranchDeleteText(dto.error.message)||dto.outcome==="uncertain"&&!["started","unknown"].includes(a.state)||dto.outcome==="failed"&&!["not-attempted","not-started"].includes(a.state))return false;if(dto.error.code==="invalid_request"&&(r!==null||c||a.state!=="not-attempted"||a.aborted)||dto.error.code==="aborted"&&!a.aborted||dto.error.code==="launch_failed"&&!["not-attempted","not-started"].includes(a.state))return false;}return true;}
export async function executeObjectDeleteOutput(action:ObjectDeleteAction,args:unknown){let dto=await assembleObjectDeleteReceipt(action,args);const valid:boolean=validateObjectDeleteOutput(dto)&&dto.action===action;if(!valid){const possible=["started","unknown"].includes(dto.data.attempt.state),d=emptyObjectDeleteData(action);if(possible){d.attempt.state="unknown";d.effect="uncertain";}dto=objectDeleteFailure(action,d,"producer_failed","Object-delete receipt validation failed; effects remain possible, no automatic retry.");if(!validateObjectDeleteOutput(dto))throw Error("Safe object-delete receipt unavailable.");}return {content:[{type:"text" as const,text:presentObjectDeleteReceipt(dto)}],details:{},structuredContent:dto,isError:!dto.ok};}
