import assert from "node:assert/strict";
import { EventEmitter } from "node:events";
import { Readable } from "node:stream";
import { mergeToBranch, runWithAbortSignal, update } from "../src/plastic-core.ts";
import { assembleCloseoutReceipt } from "../src/operations/closeout-receipt";
import { validateCloseoutOutput } from "../src/pi/closeout-output";
import { loadRegisteredTools } from "./pi-tool-harness.ts";
const tools=await loadRegisteredTools();for(const [name,t]of tools)if(name.startsWith("plastic_")&&name!=="plastic_tool_search")assert.equal((t.parameters as any)?.properties?.authorizationToken,undefined);
type Call={command:string;args:string[];cwd:string};const cwd=process.cwd();
function producer(calls:Call[],reply:(args:string[])=>{out?:string;err?:string;code?:number}){return ((command:string,args:string[],options:any)=>{calls.push({command,args:[...args],cwd:options.cwd});const r=reply(args),child=Object.assign(new EventEmitter(),{stdout:Readable.from(r.out?[Buffer.from(r.out)]:[]),stderr:Readable.from(r.err?[Buffer.from(r.err)]:[]),kill:()=>true});process.nextTick(()=>{child.emit("spawn");child.emit("close",r.code??0,null);});return child;})as any;}
const calls:Call[]=[];const out=await runWithAbortSignal(undefined,()=>update.execute({workdir:cwd}),{spawn:producer(calls,()=>({out:"Updated successfully"}))});assert.match(out,/Update command completed/);assert.match(out,/remain unverified/);assert.deepEqual(calls,[{command:process.env.PI_PLASTIC_CM_EXECUTABLE?.trim()||"cm",args:["update","--dontmerge","--noinput"],cwd}]);calls.length=0;await assert.rejects(()=>runWithAbortSignal(undefined,()=>update.execute({workdir:cwd}),{spawn:producer(calls,()=>({code:1,err:"fixture mutation failure"}))}),/Update uncertain/);assert.equal(calls.length,1);
const header="STATUS\x1f123\x1frepo\x1fserver\r\n",loaded=(branch:string)=>`${branch}@repo@server (cs:123 - head)\r\n`;
for(const rows of [`PR\x1f${cwd}\\private.txt\x1fFalse\x1f-1\x1fNO_MERGES\r\n`,`CH\x1f${cwd}\\tracked.txt\x1fFalse\x1f125\x1fNO_MERGES\r\nPR\x1f${cwd}\\private.txt\x1fFalse\x1f-1\x1fNO_MERGES\r\n`]){calls.length=0;const spawn=producer(calls,a=>({out:a.includes("--machinereadable")?header+rows:loaded("/source")}));const d=await runWithAbortSignal(undefined,()=>assembleCloseoutReceipt({source:"/source",target:"/target",workdir:cwd}),{spawn});assert(validateCloseoutOutput(d));assert(!d.ok);assert.equal(d.outcome,"blocked");assert.equal(d.data.effect,"not-attempted");assert.equal(calls.length,2);assert(calls.every(c=>c.args[0]==="status"));calls.length=0;await assert.rejects(()=>runWithAbortSignal(undefined,()=>mergeToBranch.execute({source:"/source",target:"/target",workdir:cwd}),{spawn}));assert.equal(calls.length,2);}
calls.length=0;const failParent=await runWithAbortSignal(undefined,()=>assembleCloseoutReceipt({source:"/source",workdir:cwd}),{spawn:producer(calls,a=>a[0]==="find"?{err:"private parent lookup diagnostic",code:1}:{out:loaded("/source")})});assert(validateCloseoutOutput(failParent));assert(!failParent.ok);assert.equal(calls.filter(c=>c.args[0]==="find").length,1);assert(!JSON.stringify(failParent).includes("private parent lookup diagnostic"));assert(calls.every(c=>["status","find"].includes(c.args[0])));
for(const scenario of ["failed-switch","wrong-target","failed-update"]){calls.length=0;let switched=false;await assert.rejects(()=>runWithAbortSignal(undefined,()=>mergeToBranch.execute({source:"/source",target:"/target",workdir:cwd}),{spawn:producer(calls,a=>{if(a[0]==="switch"){switched=true;return scenario==="failed-switch"?{code:1,err:"private switch failure"}:{};}if(a[0]==="update")return{code:1,err:"private partial update failure"};return{out:a.includes("--machinereadable")?header:loaded(switched&&scenario!=="wrong-target"?"/target":"/source")};})}));assert.equal(calls.filter(c=>c.args[0]==="switch").length,1);assert.equal(calls.filter(c=>c.args[0]==="update").length,scenario==="failed-update"?1:0);assert.equal(calls.filter(c=>["merge","checkin"].includes(c.args[0])).length,0);}
calls.length=0;const qualified=JSON.parse(await runWithAbortSignal(undefined,()=>mergeToBranch.execute({source:"br:/source@repo@server",preflight:true,format:"json",workdir:cwd}),{spawn:producer(calls,a=>({out:a[0]==="find"?"/source|/parent\r\n":a.includes("--machinereadable")?header:loaded("/source")}))}));assert(validateCloseoutOutput(qualified));assert(qualified.ok);assert.equal(qualified.data.targetBranch,"/parent@repo@server");assert.equal(qualified.data.targetSource,"parent-read");assert.match(calls.find(c=>c.args[0]==="find")!.args[2],/where name = '\/source' on repository 'repo@server'/);assert.equal(qualified.data.targetVerification,"unverified","Preview does not verify a not-yet-loaded target");
for(const output of ["/main|\r\n","","missing-separator\r\n","/source|/main\r\n/source|/other\r\n"]){calls.length=0;const d=await runWithAbortSignal(undefined,()=>assembleCloseoutReceipt({source:"/source",preflight:true,workdir:cwd}),{spawn:producer(calls,a=>({out:a[0]==="find"?output:a.includes("--machinereadable")?header:loaded("/current")}))});assert(validateCloseoutOutput(d));assert(!d.ok);assert.equal(d.data.targetBranch,null);assert(calls.every(c=>["status","find"].includes(c.args[0])));}
calls.length=0;const explicit=await runWithAbortSignal(undefined,()=>assembleCloseoutReceipt({source:"/source",target:"/target",preflight:true,workdir:cwd}),{spawn:producer(calls,a=>({out:a.includes("--machinereadable")?header:loaded("/current")}))});assert(validateCloseoutOutput(explicit));assert(explicit.ok);assert.equal(calls.filter(c=>c.args[0]==="find").length,0);
console.log("PASS: direct update one-command/no retry, strict actual closeout cancel/parent/target/update barriers, native receipts vs core rejection, preserved qualified parent operand without alias/global scope claims or raw diagnostics");
