import assert from "node:assert/strict";
import { EventEmitter } from "node:events";
import { PassThrough } from "node:stream";
import { runWithAbortSignal } from "../src/execution/context";
import { executeObjectWriteOutput, validateObjectWriteOutput } from "../src/pi/object-write-output";
import { OBJECT_WRITE_ACTIONS, objectWriteArgv, type ObjectWriteAction } from "../src/operations/object-write-receipt";
import { shelvesetCreate, shelvesetApply } from "../src/operations/shelvesets";
import { codeReviewCreate, codeReviewUpdate } from "../src/operations/reviews";
import { loadRegisteredTools } from "./pi-tool-harness";
const cwd=process.cwd(),calls:string[][]=[];
const bases={"shelveset-create":{comment:"Fixture",paths:["owned.txt"]},"shelveset-apply":{shelveset:"sh:7@Example Repository@example@unity"},"code-review-create":{target:"br:/main/fixture@Example Repository@example@unity",title:"Fixture"},"code-review-update":{id:"9007199254740993"}};
const core={"shelveset-create":shelvesetCreate,"shelveset-apply":shelvesetApply,"code-review-create":codeReviewCreate,"code-review-update":codeReviewUpdate};
const native={"shelveset-create":"plastic_shelvesetCreate","shelveset-apply":"plastic_shelvesetApply","code-review-create":"plastic_codeReviewCreate","code-review-update":"plastic_codeReviewUpdate"};
type Reply={out?:Buffer|string;err?:Buffer|string;code?:number;start?:boolean;throw?:boolean;mutate?:()=>void};
function deps(reply:Reply){return {spawn:((_:string,a:string[])=>{calls.push([...a]);if(reply.throw)throw Error("PRIVATE_LAUNCH_FAILURE");const c=Object.assign(new EventEmitter(),{stdout:new PassThrough(),stderr:new PassThrough(),kill:()=>false});queueMicrotask(()=>{if(reply.start!==false)c.emit("spawn");reply.mutate?.();c.stdout.end(reply.out??"");c.stderr.end(reply.err??"");c.emit("close",reply.code??0,null);});return c;})as any};}
async function invoke(a:ObjectWriteAction,args:unknown,reply:Reply={}){calls.length=0;const d=await runWithAbortSignal(undefined,()=>executeObjectWriteOutput(a,args),deps(reply));assert(validateObjectWriteOutput(d.structuredContent),JSON.stringify(d));assert.deepEqual(d.details,{});return d;}
const tools=await loadRegisteredTools();assert.equal([...tools.values()].filter(t=>t.outputSchema).length,27);
for(const a of OBJECT_WRITE_ACTIONS){const request={...bases[a],workdir:cwd},out=a==="shelveset-create"?"sh:7@Example Repository@example@unity\r\n":a==="code-review-create"?"9007199254740993\r\n":"";
    for(const bad of [null,[],...(a==="shelveset-create"?[]:[{}]), {...request,preflight:"true"},{...request,output:"markdown"},{...request,extra:true},{...request,workdir:"x\n"},{...request,output:null}]){const d=await invoke(a,bad);assert(d.isError);assert.equal(calls.length,0);assert.equal(d.structuredContent.data.requested,null);}
    for(const output of ["text","json"]){const d=await invoke(a,{...request,preflight:true,output},{out});assert(!d.isError);assert.equal(d.structuredContent.outcome,"preflight");assert.equal(calls.length,0);assert.equal(d.structuredContent.data.commandOutput,null);assert.equal(d.structuredContent.data.effect,"not-attempted");}
    const ok=await invoke(a,request,{out});assert(!ok.isError);assert.equal(calls.length,1);assert.equal(ok.structuredContent.data.observedUpdatedState,null);assert.equal(ok.structuredContent.data.observedAppliedItems,null);assert.equal(ok.structuredContent.data.observedRepositoryIdentity,null);
    assert.deepEqual(calls[0],objectWriteArgv(a,ok.structuredContent.data.requested!));assert.equal(ok.structuredContent.data.effect,a.endsWith("create")?"identity-emitted":"not-proven");
    for(const mutate of [(d:any)=>d.data.intendedArgv.push("--force"),(d:any)=>d.data.attempt.exitCode=1,(d:any)=>d.data.capture.stdoutBytes++,(d:any)=>d.data.effect="not-attempted",(d:any)=>d.data.observedUpdatedState="Reviewed",(d:any)=>d.completeness.capture="unknown",(d:any)=>d.data.observedCreatedIdentity={kind:"code-review",value:"guessed",basis:"default-scalar"}]){const d=structuredClone(ok.structuredContent);mutate(d);assert(!validateObjectWriteOutput(d));}
    for(const reply of [{out,code:1,err:"PRIVATE_DIAGNOSTIC"},{out:Buffer.from([255])},{out:"x".repeat(65537)},{throw:true},{start:false,out}]){const d=await invoke(a,request,reply);assert(d.isError);assert.equal(calls.length,1);assert.equal(d.structuredContent.data.commandOutput,null);assert.equal(d.structuredContent.data.observedCreatedIdentity,null);assert.doesNotMatch(JSON.stringify(d),/PRIVATE_DIAGNOSTIC|PRIVATE_LAUNCH/);}
    const warning=await invoke(a,request,{out,err:"PRIVATE_WARNING"});assert(warning.isError);assert.equal(warning.structuredContent.outcome,"uncertain");assert.equal(warning.structuredContent.data.effect,a.endsWith("create")?"identity-emitted":"uncertain");assert.equal(warning.structuredContent.data.observedCreatedIdentity?.value,a==="shelveset-create"?"sh:7@Example Repository@example@unity":a==="code-review-create"?"9007199254740993":undefined);assert.doesNotMatch(JSON.stringify(warning),/PRIVATE_WARNING/);
    const caller:any={...request};const snapshot=await invoke(a,caller,{out,mutate:()=>{caller.preflight=true;caller.workdir="other";}});assert(!snapshot.isError);assert.equal(snapshot.structuredContent.data.requested!.workdir,cwd);assert.equal(snapshot.structuredContent.data.requested!.preflight,false);
    calls.length=0;const text=await runWithAbortSignal(undefined,()=>core[a].execute({...request,output:"json"}),deps({out}));assert.equal(JSON.parse(text).action,a);await assert.rejects(()=>runWithAbortSignal(undefined,()=>core[a].execute(request),deps({code:1})));assert.equal(calls.length,2);
    const old=core[a].execute;core[a].execute=async()=>{throw Error("Never parse core presentation");};try{const r=await runWithAbortSignal(undefined,()=>tools.get(native[a])!.execute("fixture",{...request,preflight:true}),deps({out}));assert(validateObjectWriteOutput(r.structuredContent));assert(!r.isError);const ctxArgs:any={...request,preflight:true};delete ctxArgs.workdir;const ctxResult=await tools.get(native[a])!.execute("ctx-default",ctxArgs,undefined,undefined,{cwd:"Fictional Workspace"});assert.equal(ctxResult.structuredContent.data.requested.workdir,"Fictional Workspace");}finally{core[a].execute=old;}
    const controller=new AbortController();controller.abort();calls.length=0;const aborted=await runWithAbortSignal(controller.signal,()=>executeObjectWriteOutput(a,request),deps({out}));assert(validateObjectWriteOutput(aborted.structuredContent));assert(aborted.isError);assert.equal(calls.length,0);assert.equal(aborted.structuredContent.data.effect,"not-attempted");
    for(const terminal of [false,true]){calls.length=0;const child=Object.assign(new EventEmitter(),{stdout:new PassThrough(),stderr:new PassThrough(),kill:()=>false});const retired=await runWithAbortSignal(undefined,()=>executeObjectWriteOutput(a,request),{timeoutMs:1,abortKillDelayMs:1,spawn:((_c:string,args:string[])=>{calls.push(args);queueMicrotask(()=>{child.emit("spawn");child.stdout.write("partial");if(terminal)child.emit("close",0,null);});return child;})as any});assert(validateObjectWriteOutput(retired.structuredContent));assert(retired.isError);assert.equal(retired.structuredContent.outcome,"uncertain");assert.equal(retired.structuredContent.data.attempt.terminal,terminal?"observed":"not-observed");assert.equal(calls.length,1);const frozen=JSON.stringify(retired);child.emit("error",Error("late"));child.emit("close",0,null);assert.equal(JSON.stringify(retired),frozen);}
}
for(const args of [{paths:["--all"]},{paths:Array(1)},{paths:Array(257).fill("x")},{comment:"x",commentsFile:"x"},{all:"false"},{summaryFormat:1},{dependencies:null},{comment:" "}]){const d=await invoke("shelveset-create",{...bases["shelveset-create"],...args,workdir:cwd});assert(d.isError);assert.equal(calls.length,0);}
const list=Array(256).fill("owned.txt"),many=await invoke("shelveset-create",{paths:list,comment:"Fixture",workdir:cwd,preflight:true,all:true,dependencies:true,summaryFormat:true});assert(!many.isError);assert.equal(many.structuredContent.data.intendedArgv.length,262);
const callerPaths={paths:["one"],comment:"multi\nline",workdir:cwd},paths=await invoke("shelveset-create",callerPaths,{out:"sh:9@Example Repository@example@unity",mutate:()=>callerPaths.paths.push("later")});assert(!paths.isError);assert.deepEqual((paths.structuredContent.data.requested as any).paths,["one"]);
const previous=process.env.PLASTICEDITOR;try{process.env.PLASTICEDITOR="configured editor";const blocked=await invoke("shelveset-create",{workdir:cwd});assert(blocked.isError);assert.equal(blocked.structuredContent.error!.code,"editor_configured");assert.equal(calls.length,0);const preview=await invoke("shelveset-create",{workdir:cwd,preflight:true});assert(!preview.isError);assert.equal(calls.length,0);}finally{if(previous===undefined)delete process.env.PLASTICEDITOR;else process.env.PLASTICEDITOR=previous;}
for(const comparisonMethod of ["ignoreeol","ignorewhitespaces","ignoreeolandwhitespaces","recognizeall"]){const d=await invoke("shelveset-apply",{...bases["shelveset-apply"],changePaths:["/a.txt","/a.txt"],preview:true,dontCheckout:true,comparisonMethod,workdir:cwd},{out:"preview output"});assert(!d.isError);assert.equal(calls.length,1);assert(calls[0].includes("--preview"));assert.equal(d.structuredContent.data.effect,"not-proven");}
for(const args of [{shelveset:"-"},{preview:"true"},{comparisonMethod:"force"},{changePaths:["--all"]}]){const d=await invoke("shelveset-apply",{...bases["shelveset-apply"],...args,workdir:cwd});assert(d.isError);assert.equal(calls.length,0);}
for(const format of ["{0}","{1}","{id} -> {guid}","json","{0}\n{1}",""]){const d=await invoke("code-review-create",{...bases["code-review-create"],format,workdir:cwd},{out:"9007199254740993\r\n"});assert(!d.isError);assert.equal(d.structuredContent.data.commandOutput!.text,"9007199254740993\r\n");assert.equal(d.structuredContent.data.observedCreatedIdentity===null,!!format);assert.equal(calls[0].includes("--format="+format),!!format);}
const options=await invoke("code-review-update",{id:"aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee",status:"Reviewed",assignee:"Fictional Reviewer",repository:"Example Repository@example@unity",workdir:cwd});assert(!options.isError);assert.deepEqual(calls[0],["codereview","-e","aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee","--status=Reviewed","--assignee=Fictional Reviewer","--repository=Example Repository@example@unity"]);assert.equal(options.structuredContent.data.observedUpdatedState,null);
for(const [name,args] of [["plastic_shelvesetCreate",{cwd,items:["one"],summary_format:true}],["plastic_shelvesetApply",{cwd,change_paths:["/one"],dont_checkout:true,comparison_method:"ignoreeol"}],["plastic_codeReviewUpdate",{cwd,review_id:"7",id:"9"}]]as const){const original=structuredClone(args),prepared=tools.get(name)!.prepareArguments!(args);assert.deepEqual(args,original);assert.equal(prepared.workdir,cwd);assert(!Object.hasOwn(prepared,"cwd"));if(name==="plastic_codeReviewUpdate")assert.equal(prepared.id,"9");}
console.log("PASS: four typed object-write receipts, exact immutable requests/argv/defaults/aliases/formatting, scalar identity vs opaque progress/state, preflight vs CLI preview, editor barrier, uncertainty/bounds/retirement/core/native and no hidden reads/retries");
