import assert from "node:assert/strict";
import {EventEmitter} from "node:events";import {Readable,PassThrough} from "node:stream";
import {executeBranchDeleteOutput,validateBranchDeleteOutput} from "../src/pi/branch-delete-output";
import {branchDelete} from "../src/operations/branches";import {emptyBranchDeleteData} from "../src/operations/branch-delete-receipt";
import {runWithAbortSignal} from "../src/execution/context";import {loadRegisteredTools} from "./pi-tool-harness";
const cwd="C:\\Example\\workspace";let calls:string[][]=[];
const fake=(out=Buffer.alloc(0),err=Buffer.alloc(0),code=0,mode="normal")=>({spawn:((_cmd:string,args:string[],options:any)=>{calls.push([...args]);assert.equal(options.cwd,cwd);assert.equal(options.shell,false);if(mode==="throw")throw Error("PRIVATE launch");const child=Object.assign(new EventEmitter(),{stdout:Readable.from([out]),stderr:Readable.from([err]),kill:()=>true});queueMicrotask(()=>{if(mode!=="missing-start")child.emit("spawn");child.emit("close",code,null);});return child;})as any});
for(const branch of ["/main/fixture","main/task002","relative","br:/main/café-é-日本-😀","/main/space name@Example Repository@example@unity","/main/PRIVATE","x".repeat(4096)])for(const deleteChangesets of [false,true]){
 calls=[];const r=await runWithAbortSignal(undefined,()=>executeBranchDeleteOutput({branch,deleteChangesets,workdir:cwd}),fake());assert(validateBranchDeleteOutput(r.structuredContent));assert(r.structuredContent.ok);assert.deepEqual(calls,[["branch","delete",branch,...deleteChangesets?["--delete-changesets"]:[]]]);assert.equal(r.structuredContent.data.observedDeletedBranch,null);assert.deepEqual(r.details,{});
 for(const mutate of [(v:any)=>v.data.requestedBranch="foreign",(v:any)=>v.data.deleteChangesetsRequested=!deleteChangesets,(v:any)=>v.data.intendedArgv.push("--recursive"),(v:any)=>v.data.observedDeletedBranch=branch,(v:any)=>v.data.observedDeletedChangesets=[],(v:any)=>v.data.attempt.exitCode=1,(v:any)=>v.data.capture.complete=false,(v:any)=>v.data.requestedBranch=null,(v:any)=>v.data.extra=true,(v:any)=>v.extra=true]){const v=structuredClone(r.structuredContent);mutate(v);assert(!validateBranchDeleteOutput(v));}
}
for(const branch of [null,1,"","  ","-","--delete-changesets"," --other","x\ny","\uD800","x".repeat(4097)]){calls=[];const r=await runWithAbortSignal(undefined,()=>executeBranchDeleteOutput({branch,workdir:cwd}),fake());assert(validateBranchDeleteOutput(r.structuredContent));assert(r.isError);assert.equal(calls.length,0);}
for(const input of [null,[],{}, {branch:"x",deleteChangesets:null},{branch:"x",deleteChangesets:"true"},{branch:"x",preflight:null},{branch:"x",format:null},{branch:"x",format:"yaml"},{branch:"x",workdir:null},{branch:"x",extra:true}]){calls=[];const r=await runWithAbortSignal(undefined,()=>executeBranchDeleteOutput(input),fake());assert(validateBranchDeleteOutput(r.structuredContent));assert(r.isError);assert.equal(calls.length,0);}
for(const [out,err,code,mode,outcome] of [[Buffer.from("opaque PRIVATE id"),Buffer.from("PRIVATE warning"),0,"normal","command-completed"],[Buffer.from("partial"),Buffer.from("PRIVATE failure"),1,"normal","uncertain"],[Buffer.from([255]),Buffer.alloc(0),0,"normal","uncertain"],[Buffer.alloc(65537),Buffer.alloc(0),0,"normal","uncertain"],[Buffer.alloc(0),Buffer.alloc(16385),0,"normal","uncertain"],[Buffer.alloc(0),Buffer.alloc(0),0,"missing-start","uncertain"],[Buffer.alloc(0),Buffer.alloc(0),0,"throw","failed"]] as const){calls=[];const r=await runWithAbortSignal(undefined,()=>executeBranchDeleteOutput({branch:"/main/fixture",workdir:cwd}),fake(out,err,code,mode));assert(validateBranchDeleteOutput(r.structuredContent));assert.equal(r.structuredContent.outcome,outcome);assert.equal(r.isError,outcome!=="command-completed");assert.equal(calls.length,1);assert.doesNotMatch(JSON.stringify(r),/PRIVATE|opaque|partial/);}
for(const format of ["text","json"] as const)for(const deleteChangesets of [false,true]){calls=[];const r=await runWithAbortSignal(undefined,()=>executeBranchDeleteOutput({branch:"/main/fixture",deleteChangesets,preflight:true,format,workdir:cwd}),fake());assert(validateBranchDeleteOutput(r.structuredContent));assert.equal(r.structuredContent.outcome,"preflight");assert.equal(calls.length,0);const bad=structuredClone(r.structuredContent);bad.data.attempt.state="started";assert(!validateBranchDeleteOutput(bad));const core=await runWithAbortSignal(undefined,()=>branchDelete.execute({branch:"fixture",deleteChangesets,preflight:true,format,workdir:cwd}),fake());assert.match(core,format==="json"? /"outcome":"preflight"/:/command-only preview/);assert.equal(calls.length,0);}
calls=[];await assert.rejects(runWithAbortSignal(undefined,()=>branchDelete.execute({branch:"/main/fixture",workdir:cwd}),fake(Buffer.from("partial"),Buffer.from("PRIVATE"),1)),/Branch deletion uncertain/);assert.equal(calls.length,1);
const controller=new AbortController();controller.abort();calls=[];const aborted=await runWithAbortSignal(controller.signal,()=>executeBranchDeleteOutput({branch:"/main/fixture",workdir:cwd}),fake());assert(validateBranchDeleteOutput(aborted.structuredContent));assert(aborted.structuredContent.data.attempt.aborted);assert.equal(calls.length,0);
const tools=await loadRegisteredTools();for(const input of [{branch:"/main/fixture",cwd,delete_changesets:true,format:"markdown"},{branch:"canonical",workdir:cwd,cwd:"shadow",deleteChangesets:false,delete_changesets:true}]){const original=structuredClone(input),prepared=tools.get("plastic_branchDelete")!.prepareArguments!(input);assert.deepEqual(input,original);calls=[];const r=await runWithAbortSignal(undefined,()=>tools.get("plastic_branchDelete")!.execute("alias",prepared),fake());assert(validateBranchDeleteOutput(r.structuredContent));assert(r.structuredContent.ok);assert.equal(calls.length,1);assert(!("delete_changesets" in prepared));assert(!("cwd" in prepared));}
const mutable={branch:"/main/original",workdir:cwd};calls=[];const pending=runWithAbortSignal(undefined,()=>executeBranchDeleteOutput(mutable),fake());mutable.branch="--delete-changesets";const own=await pending;assert(own.structuredContent.ok);assert.deepEqual(calls,[["branch","delete","/main/original"]]);assert.deepEqual(emptyBranchDeleteData().intendedArgv,["branch","delete"]);
for(const mode of ["missing-spawn","terminal-open-pipes","timeout","abort"]){const control=new AbortController();calls=[];const child=Object.assign(new EventEmitter(),{stdout:new PassThrough(),stderr:new PassThrough(),kill:()=>false});let t:NodeJS.Timeout|undefined;const r=await runWithAbortSignal(control.signal,()=>executeBranchDeleteOutput({branch:"/main/fixture",workdir:cwd}),{spawn:((_cmd:string,args:string[])=>{calls.push([...args]);queueMicrotask(()=>{if(mode!=="missing-spawn")child.emit("spawn");if(mode==="terminal-open-pipes")child.emit("close",0,null);if(mode==="abort")control.abort();});return child;}) as any,setTimeout:((fn:()=>void)=>{t=setTimeout(fn,3);return t;})as any,abortKillDelayMs:3});assert(validateBranchDeleteOutput(r.structuredContent));assert.equal(r.structuredContent.outcome,"uncertain");assert.equal(calls.length,1);const frozen=JSON.stringify(r);child.emit("close",0,null);child.stdout.emit("data",Buffer.from("late"));assert.equal(JSON.stringify(r),frozen);}
console.log("PASS: branch-delete exact relative/qualified/Unicode/default/true flag/strict controls/preview/aliases/ownership/core/native/anti-forgery and retirement; no hidden reads/retries");
