import assert from "node:assert/strict";
import { EventEmitter } from "node:events";
import { PassThrough } from "node:stream";
import { Check } from "typebox/value";
import { assembleCloseoutReceipt } from "../src/operations/closeout-receipt";
import { closeoutOutputSchema, validateCloseoutOutput, executeCloseoutOutput } from "../src/pi/closeout-output";
import { mergeToBranch } from "../src/operations/closeout";
import { runWithAbortSignal } from "../src/execution/context";
import { TOOL_CONFIG } from "../src/pi/arguments";
import { loadRegisteredTools } from "./pi-tool-harness";
const cwd="C:\\Example\\workspace",repo="Example Repository",server="example@unity",source="/main/source",target="/main/target",request={source,target,message:"Fixture",workdir:cwd};
let branch=source,mode="success",std=0,machine=0,merged=false,pending=0;const calls:string[][]=[];
const deps={spawn:((_:string,argv:string[],options:any)=>{assert.equal(options.shell,false);calls.push([...argv]);const child=Object.assign(new EventEmitter(),{stdout:new PassThrough(),stderr:new PassThrough(),kill(){return false;}});queueMicrotask(()=>{child.emit("spawn");let out="",err="",code=0;
 if(argv[0]==="status"){
  if(argv.includes("--machinereadable")){machine++;out=`STATUS\x1f16\x1f${repo}\x1f${server}\r\n`;if(pending)out+=`CH\x1f${cwd}\\fixture.txt\x1fFalse\x1f125\x1fNO_MERGES\r\n`;if(mode==="pending-before-fail"&&machine===1||mode==="checkin-preflight-fail"&&machine===3||mode==="child-post-fail"&&machine===5||mode==="final-pending-fail"&&machine===6){code=1;err="Synthetic state read failure";}}
  else if(argv.includes("--short")){if(mode==="short-fail"){code=1;err="Synthetic short failure";}}
  else {std++;if(mode==="before-merge-drift"&&std===5||mode==="final-branch-drift"&&std===9)branch="/main/elsewhere";out=`${branch}@${repo}@${server} (cs:16 - head)\r\n\r\n`;if(mode==="full-fail"&&merged&&std===6||mode==="later-read-fail"&&std===7||mode==="final-branch-fail"&&std===9){code=1;err="Synthetic full read failure";}if(mode==="later-warning"&&std===7)err="Unknown warning on admitted stdout";if(mode==="unknown-status"&&merged)out+="Unknown merge metadata\r\n";if(mode==="initial-fail"&&std===1){code=1;err="Synthetic loaded-state failure";}}
 }else if(argv[0]==="find"){out=source+"|/main\r\n";if(mode==="parent-fail"){code=1;err="Synthetic parent failure";}if(mode==="parent-warning")err="Unknown warning";if(mode==="parent-empty")out="";if(mode==="parent-malformed")out=source+"|/main|other\r\n";}
 else if(argv[0]==="switch"){branch=target;if(mode==="switch-fail"){code=1;err="Synthetic switch failure";}}
 else if(argv[0]==="update"){assert.deepEqual(argv,["update","--dontmerge","--noinput"]);if(mode==="update-fail"){code=1;err="Synthetic update failure";}}
 else if(argv[0]==="merge"){merged=true;const sep=(k:string)=>argv.find(a=>a.startsWith(k+"="))!.slice(k.length+1);out=sep("--startlineseparator")+["STATUS","ALREADY_CONNECTED","No merges detected"].join(sep("--fieldseparator"))+sep("--endlineseparator")+"\r\n";if(mode==="partial-merge"){code=1;err="Synthetic partial apply";}if(mode==="unknown-merge")out="Unrecognized completion";}
 else if(argv[0]==="checkin"){const sep=(k:string)=>argv.find(a=>a.startsWith(k+"="))!.slice(k.length+1),frame=(op:string,...fields:string[])=>sep("--startlineseparator")+[op,...fields].join(sep("--fieldseparator"))+sep("--endlineseparator")+"\r\n";out=frame("CI_START")+frame("STAGE","");if(mode==="checkin-fail"){code=1;err="Synthetic permission denied";}else out+=frame("CHANGESET",`cs:127@br:${mode==="changeset-other-branch"?"/main/elsewhere":target}@${repo}@${mode==="changeset-other-server"?"example@cloud":server} (mount:'/')`);}
 else throw Error("Unexpected command "+JSON.stringify(argv));child.stdout.end(out);child.stderr.end(err);child.emit("close",code,null);});return child;})as any};
function reset(m="success",p=0){mode=m;std=0;machine=0;merged=false;branch=source;pending=p;calls.length=0;}
async function run(args:any=request,m="success",p=0){reset(m,p);const d=await runWithAbortSignal(undefined,()=>assembleCloseoutReceipt(args),deps);assert(Check(closeoutOutputSchema,d),"closed schema "+JSON.stringify(d));assert(validateCloseoutOutput(d),"semantics "+JSON.stringify(d));assert.equal(d.data.unobservedChild,null);return d;}
if(process.platform==="win32"){
 const caller={...request};reset();let changed=false;const mutated=await runWithAbortSignal(undefined,()=>assembleCloseoutReceipt(caller),{spawn:((...args:any[])=>{if(!changed){changed=true;caller.source="/main/late-source";caller.target="/main/late-target";caller.message="Late";}return (deps.spawn as any)(...args);})as any});assert(validateCloseoutOutput(mutated));assert(mutated.ok);assert.equal(mutated.data.requested?.source,request.source);assert.equal(mutated.data.sourceBranch,request.source);assert.equal(mutated.data.targetBranch,request.target);assert.equal(mutated.data.checkinMessage,request.message);assert.equal(calls.find(a=>a[0]==="switch")?.at(-1),request.target);
 const completed=await run();assert(completed.ok);assert.equal(completed.outcome,"completed");assert.equal(completed.data.createdChangeset?.id,"127");assert.equal(completed.data.effect,"changeset-created");assert.equal(completed.data.targetVerification,"name-only");assert.equal(completed.data.pendingAfter?.totalPending,0);assert.equal(calls.filter(a=>a[0]==="checkin").length,1);assert.equal(calls.filter(a=>a[0]==="update").length,1);assert.equal(completed.data.stages.length,13);assert.deepEqual(completed.data.unattemptedStages,["parent"]);
 const skipped=await run({...request,updateTarget:false});assert(skipped.ok);assert.equal(calls.filter(a=>a[0]==="update").length,0);assert(skipped.data.unattemptedStages.includes("update"));
 for(const [m,last] of [["initial-fail","loaded-before"],["pending-before-fail","pending-before"],["switch-fail","switch"],["update-fail","update"],["before-merge-drift","loaded-before-merge"],["short-fail","merge"],["full-fail","merge"],["later-read-fail","readiness"],["later-warning","readiness"],["unknown-status","merge"],["unknown-merge","merge"],["partial-merge","merge"],["checkin-preflight-fail","checkin-preflight"],["checkin-fail","checkin"]]){const d=await run(request,m);assert(!d.ok);assert.equal(d.data.stages.at(-1)?.name,last);assert.equal(d.data.createdChangeset,null);assert.equal(calls.filter(a=>a[0]==="checkin").length,m==="checkin-fail"?1:0);assert.equal(calls.filter(a=>a[0]==="merge").length,["initial-fail","pending-before-fail","switch-fail","update-fail","before-merge-drift"].includes(m)?0:1);}
 for(const m of ["final-branch-fail","final-branch-drift","final-pending-fail","changeset-other-branch","changeset-other-server"]){const d=await run(request,m);assert(!d.ok);assert.equal(d.outcome,"uncertain");assert.equal(d.data.createdChangeset?.id,"127");assert.equal(d.data.effect,"changeset-created");assert.equal(d.data.pendingAfter,null);assert.equal(calls.filter(a=>a[0]==="checkin").length,1);assert(!calls.some(a=>a[0]==="undo"));}
 const childPost=await run(request,"child-post-fail");assert(childPost.ok);assert.equal(childPost.data.createdChangeset?.id,"127");assert.equal(childPost.completeness.capture,"complete");assert(childPost.data.stages.some(s=>s.kind==="checkin"&&s.name==="checkin"&&s.result.data.pendingAfter===null)); // independent final read is separately positive, failed exit1 capture itself complete
 const blocked=await run(request,"success",1);assert(!blocked.ok);assert.equal(blocked.outcome,"blocked");assert.equal(blocked.data.effect,"not-attempted");assert(calls.every(a=>a[0]==="status"));
 const preview=await run({...request,preflight:true},"success",1);assert(preview.ok);assert.equal(preview.outcome,"preflight");assert.equal(calls.length,2);assert(calls.every(a=>a[0]==="status"));
 for(const m of ["parent-fail","parent-warning","parent-empty","parent-malformed"]){const d=await run({source,preflight:true,workdir:cwd},m);assert(!d.ok);assert.equal(calls.filter(a=>a[0]==="find").length,1);assert(calls.every(a=>["status","find"].includes(a[0])));}
 const defaults=await run({preflight:true,workdir:cwd});assert(defaults.ok);assert.equal(defaults.data.sourceBranch,source);assert.equal(defaults.data.targetBranch,"/main");assert.equal(defaults.data.requested?.strategy,"auto");assert.equal(defaults.data.requested?.updateTarget,true);assert.equal(defaults.data.requested?.includePrivate,false);assert.equal(defaults.data.requested?.outputFormat,"text");
 const qualified=await run({...request,source:`br:${source}@${repo}@${server}`,target:`br:${target}@${repo}@${server}`});assert(qualified.ok);assert.equal(qualified.data.targetVerification,"exact-qualifier-spelling");
 for(const k of ["source","target"]){const d=await run({...request,[k]:`${k==="source"?source:target}@${repo}@example@cloud`});assert(!d.ok);assert.equal(d.data.effect,"not-attempted");assert.equal(calls.length,1);}
 const sameBranch=await run({...request,target:source});assert(!sameBranch.ok);assert.equal(calls.length,1);
 const card=await run({source,target,cardRef:"$fictional",workdir:cwd});assert(card.ok);assert.equal(calls.filter(a=>a[0]==="checkin").length,1);assert.equal(card.data.checkinMessage,`Merge ${source} into ${target}\n\n$fictional`);assert(calls.find(a=>a[0]==="checkin")!.includes(`-c=${card.data.checkinMessage}`));const override=await run({...request,cardRef:"$fictional"});assert(override.ok);assert.equal(override.data.checkinMessage,"Fixture");
 for(const invalid of [{source:"cs:16"},{target:"label:sample"},{source:"-"},{target:" --to=x"},{source:null},{target:"/main/\ud800"},{source:"/main\nother"},{updateTarget:null},{includePrivate:1},{preflight:"true"},{strategy:"guess"},{format:"markdown"},{rogue:true},{message:"bad\n\0text"},{message:"bad\ttext"},{cardRef:"bad\ntext"},{workdir:cwd+"\nother"},{target:target+"\r\nother"},{workdir:"x".repeat(4097)}]){const d=await run({...request,...invalid});assert(!d.ok);assert.equal(d.data.requested,null);assert.equal(calls.length,0);}
 const unknown:any=structuredClone(completed);unknown.ok=false;unknown.outcome="uncertain";unknown.error={code:"producer_failed",stage:"merge",message:"Unknown child start"};unknown.data.stages=unknown.data.stages.slice(0,6);unknown.data.unobservedChild="merge";unknown.data.createdChangeset=null;unknown.data.pendingAfter=null;unknown.data.effect="uncertain";unknown.completeness.capture="incomplete";const all=["loaded-before","parent","pending-before","switch","loaded-after-switch","update","loaded-before-merge","merge","readiness","loaded-before-checkin","checkin-preflight","checkin","loaded-final","pending-final"];unknown.data.unattemptedStages=all.filter(n=>n!=="merge"&&!unknown.data.stages.some((s:any)=>s.name===n));assert(validateCloseoutOutput(unknown));const erased=structuredClone(unknown);erased.data.unobservedChild=null;assert(!validateCloseoutOutput(erased));
 for(const mutate of [(d:any)=>d.extra=true,(d:any)=>d.data.requested=null,(d:any)=>d.data.createdChangeset=null,(d:any)=>d.data.stages.splice(8,1),(d:any)=>d.data.stages[6].result.data.requestedSource="/main/elsewhere",(d:any)=>d.data.pendingAfter.totalPending=10,(d:any)=>d.data.targetVerification="exact-qualifier-spelling",(d:any)=>d.data.stages[8].result.admission="unsupported",(d:any)=>d.data.unattemptedStages=[],(d:any)=>d.data.createdChangeset.server="elsewhere@cloud"]){const d=structuredClone(completed);mutate(d);assert(!validateCloseoutOutput(d),"Forged ledger rejected");}
 reset("later-warning");await assert.rejects(()=>runWithAbortSignal(undefined,()=>mergeToBranch.execute(request),deps));assert.equal(calls.filter(a=>a[0]==="checkin").length,0);
 reset();const core=JSON.parse(await runWithAbortSignal(undefined,()=>mergeToBranch.execute({...request,format:"json"}),deps));assert(validateCloseoutOutput(core));assert.equal(core.data.createdChangeset.id,"127");
 reset("initial-fail");const native=await runWithAbortSignal(undefined,()=>executeCloseoutOutput({...request,preflight:true}),deps);assert(native.isError);assert(validateCloseoutOutput(native.structuredContent));assert.deepEqual(native.details,{});assert(!native.content[0].text.includes("Preview returned"));
 const args={sourceBranch:source,target_branch:target,card:"$fictional",update:false,include_private:false,cwd,message:"Fixture",format:"markdown"},prepared=TOOL_CONFIG.mergeToBranch!.prepareArguments!(args);assert.deepEqual(prepared,{source,target,cardRef:"$fictional",updateTarget:false,includePrivate:false,workdir:cwd,message:"Fixture",format:"text"});assert.equal(args.format,"markdown");assert.equal(TOOL_CONFIG.mergeToBranch!.prepareArguments!({...args,source:"/main/canonical"}).source,"/main/canonical");
 const tools=await loadRegisteredTools();assert(tools.get("plastic_mergeToBranch")?.outputSchema);reset();const registered=await runWithAbortSignal(undefined,()=>tools.get("plastic_mergeToBranch")!.execute("native",{...request,preflight:true}),deps);assert(validateCloseoutOutput(registered.structuredContent));assert(registered.structuredContent.ok);assert.deepEqual(registered.details,{});
 for(const newline of ["\n","\r\n","\r"]){
  const message=`  Fixture 😀${newline}Details${newline}  `;
  const d=await run({...request,message});assert(d.ok);assert.equal(d.data.checkinMessage,message);assert.equal(d.data.requested?.message,message);assert.deepEqual(calls.find(a=>a[0]==="checkin")!.filter(a=>a.startsWith("-c=")),[`-c=${message}`]);
  reset();const result=await runWithAbortSignal(undefined,()=>tools.get("plastic_mergeToBranch")!.execute("fixture",{...request,message}),deps);assert(validateCloseoutOutput(result.structuredContent));assert(result.structuredContent.ok);assert.equal(result.structuredContent.data.checkinMessage,message);assert.deepEqual(calls.find(a=>a[0]==="checkin")!.filter(a=>a.startsWith("-c=")),[`-c=${message}`]);
 }
}else {const d=await assembleCloseoutReceipt(request);assert(!d.ok);assert(validateCloseoutOutput(d));}
console.log("PASS: actual typed child composition, bounded admission/defaults/aliases/discovery, qualifier-sensitive target gates, checkin/final-read effects, preview/native/core and closed semantic anti-forgery; no child stubs, mutation replay or compensation");
