import { resolve } from "node:path";
import { parseSwitchTarget, parseSwitchLoadedBranch, compareSwitchTarget, parseSwitchPending, switchPendingArgv, safeSwitchValue } from "../domain/switch-contract";
import { checkinSafeValue } from "../domain/checkin-contract";
import { admitCleanStandardStatus } from "../domain/workspace-merge-contract";
import { parseCopiedPending } from "../domain/copied-merge";
import { cmWhereEquals } from "../domain/branches";
import { CLOSEOUT_STAGE_NAMES, closeoutChildEffect, closeoutCaptures, type CloseoutData, type CloseoutReceipt, type CloseoutRequest, type CloseoutStageName, type CloseoutRead, type CloseoutStage } from "../domain/closeout-contract";
import { captureWorkspaceMergeCommand, emptyWorkspaceMergeAttempt } from "../execution/workspace-merge-command";
import { assembleSwitchReceipt } from "./switch-receipt";
import { assembleUpdateReceipt } from "./update-receipt";
import { assembleWorkspaceMergeReceipt } from "./workspace-merge-receipt";
import { assembleCheckinReceipt } from "./checkin-receipt";
export { presentCloseoutReceipt } from "../presentation/closeout-results";
export { CLOSEOUT_STAGE_NAMES, CLOSEOUT_DTO_BYTES, closeoutChildEffect, closeoutCaptures } from "../domain/closeout-contract";
export type { CloseoutReceipt, CloseoutStage, CloseoutRead } from "../domain/closeout-contract";
export { compareSwitchTarget, parseSwitchTarget, safeSwitchValue, switchPendingArgv } from "../domain/switch-contract";
export { checkinSafeValue } from "../domain/checkin-contract";
export { cmWhereEquals } from "../domain/branches";
export function emptyCloseoutData(): CloseoutData { return {requested:null,sourceBranch:null,targetBranch:null,targetSource:"unresolved",checkinMessage:null,stages:[],unattemptedStages:[...CLOSEOUT_STAGE_NAMES],unobservedChild:null,createdChangeset:null,pendingAfter:null,targetVerification:"unverified",serverAliasEquivalence:"unverified",sourceLink:"unverified",branchHead:"unverified",exclusiveScope:"unverified",rollback:"not-proven",effect:"not-attempted"}; }
function admitRequest(input:unknown):asserts input is CloseoutRequest { if(!input||typeof input!=="object"||Array.isArray(input))throw Error();const r=input as Record<string,unknown>;if(Object.keys(r).some(k=>!["source","target","message","cardRef","strategy","updateTarget","includePrivate","preflight","format","workdir"].includes(k)))throw Error();for(const k of ["source","target"])if(r[k]!==undefined&&(!safeSwitchValue(r[k])||!parseSwitchTarget(r[k])))throw Error();for(const k of ["message","cardRef"])if(r[k]!==undefined&&!checkinSafeValue(r[k]))throw Error();if(r.workdir!==undefined&&!safeSwitchValue(r.workdir))throw Error();if(r.strategy!==undefined&&!["auto","source","destination"].includes(r.strategy as string)||r.format!==undefined&&!["text","json"].includes(r.format as string))throw Error();for(const k of ["updateTarget","includePrivate","preflight"])if(r[k]!==undefined&&typeof r[k]!=="boolean")throw Error();if(Buffer.byteLength(JSON.stringify(r),"utf8")>32768)throw Error(); }
export async function assembleCloseoutReceipt(input:unknown):Promise<CloseoutReceipt> {
 const data=emptyCloseoutData();let stage:"input"|CloseoutStageName|"producer"="input";let childEntered=false;
 const finish=(outcome:CloseoutReceipt["outcome"],code:Extract<CloseoutReceipt,{ok:false}>["error"]["code"]="observation_failed",message="Closeout paused; inspect earlier effects before deciding whether to retry."):CloseoutReceipt=>{
  const effects=data.stages.map(closeoutChildEffect);data.effect=data.createdChangeset?"changeset-created":effects.includes("uncertain")||childEntered?"uncertain":effects.includes("command-completed")?"command-completed":"not-attempted";
  const captures=closeoutCaptures(data.stages),projection=data.stages.every(s=>s.kind==="read"||s.result.completeness.projection);
  const ok=outcome==="completed"||outcome==="preflight";const actual=!ok&&data.effect!=="not-attempted"?"uncertain":outcome;
  return {schemaVersion:1,action:"merge-to-branch",provenance:{source:"plastic",producer:"@aefree/pi-plastic",contentTrust:"external"},completeness:{capture:!captures.length?"unknown":!data.unobservedChild&&data.stages.every(s=>s.kind!=="read"||s.result.capture!==null)&&captures.every(c=>c.complete)?"complete":"incomplete",projection},data,ok,outcome:actual,...(!ok?{error:{code,stage,message}}:{})} as CloseoutReceipt;
 };
 const push=(s:CloseoutStage)=>{if(data.stages.length>=16)throw Error();data.stages.push(s);data.unattemptedStages=data.unattemptedStages.filter(n=>n!==s.name);};
 const read=async(name:CloseoutStageName,argv:string[])=>{stage=name;const s:CloseoutRead={argv:[...argv],attempt:{...emptyWorkspaceMergeAttempt(),state:"unknown"},capture:null,admission:"unsupported",branch:null,parentPath:null,emptyParentResult:false,summary:null};push({name,kind:"read",result:s});const o=await captureWorkspaceMergeCommand([...argv],data.requested!.workdir);s.attempt=o.attempt;s.capture=o.capture;const success=o.capture.complete&&!o.failed&&o.attempt.state==="started"&&o.attempt.terminal==="observed"&&o.attempt.exitCode===0&&!o.attempt.aborted&&!o.attempt.timedOut&&o.stderr===""&&o.stdout!==null;return {s,o,success};};
 const loaded=async(name:CloseoutStageName,verify=false)=>{const {s,o,success}=await read(name,["status"]);if(success){s.branch=parseSwitchLoadedBranch(o.stdout!);if(s.branch)s.admission="admitted";}if(!s.branch)return false;if(verify){data.targetVerification=compareSwitchTarget(s.branch,data.targetBranch!);if(data.targetVerification==="unverified")return false;}return true;};
 const pending=async(name:"pending-before"|"pending-final")=>{const {s,o,success}=await read(name,[...switchPendingArgv]);if(success){const p=parseSwitchPending(o.stdout!,data.requested!.workdir);if(p.summary){s.admission="admitted";s.summary=p.summary;}}return s.summary;};
 try{
  const submitted=input&&typeof input==="object"&&!Array.isArray(input)?Object.freeze({...input}):input;admitRequest(submitted);const cwd=submitted.workdir??process.cwd();if(!safeSwitchValue(cwd)||!safeSwitchValue(resolve(cwd)))return finish("failed","invalid_request","Closeout needs a bounded workdir.");data.requested={source:submitted.source??null,target:submitted.target??null,message:submitted.message??null,cardRef:submitted.cardRef??null,strategy:submitted.strategy??"auto",updateTarget:submitted.updateTarget??true,includePrivate:submitted.includePrivate??false,preflight:submitted.preflight??false,outputFormat:submitted.format??"text",workdir:cwd};
  if(process.platform!=="win32")return finish("failed","unsupported_source","Closeout source is admitted only on observed Windows/client configuration.");
  if(!await loaded("loaded-before"))return finish("failed");const start=(data.stages[0] as Extract<CloseoutStage,{kind:"read"}>).result.branch!;data.sourceBranch=submitted.source??start.branch;
  const source=parseSwitchTarget(data.sourceBranch)!;const inScope=(spec:string)=>{const t=parseSwitchTarget(spec)!;return t.repository===null||t.repository===start.repository&&t.server===start.server;};
  if(!inScope(data.sourceBranch)||submitted.target!==undefined&&!inScope(submitted.target))return finish("failed","target_unverified","Qualified branch repository/server spelling differs from the observed workspace; alias equivalence is unverified. No target mutation permitted.");
  if(submitted.target!==undefined){data.targetBranch=submitted.target;data.targetSource="explicit";}
  else{
   const candidates=source.repository!==null?[source.branch]:[...new Set([data.sourceBranch,source.branch,`br:${source.branch}`])];let resolved=false;
   for(const candidate of candidates){const clause=source.repository===null?"":` on repository '${(source.repository+"@"+source.server).replace(/'/g,"''")}'`;const {s,o,success}=await read("parent",["find","branch",`where ${cmWhereEquals("name",candidate)}${clause}`,"--format={name}|{parent}","--nototal"]);if(!success)return finish("failed");const lines=o.stdout!.split(/\r?\n/);if(lines.at(-1)==="")lines.pop();if(!lines.length){s.admission="admitted";s.emptyParentResult=true;continue;}if(lines.length!==1)return finish("failed");const f=lines[0].split("|");if(f.length!==2||f[0]!==source.branch||!parseSwitchTarget(f[0])||!f[1]||!parseSwitchTarget(f[1])||parseSwitchTarget(f[1])!.repository!==null)return finish("failed","observation_failed","Parent read did not admit one matching branch and parent path; pass an explicit target.");s.parentPath=f[1];s.admission="admitted";const target=source.repository===null?f[1]:`${f[1]}@${source.repository}@${source.server}`;if(!parseSwitchTarget(target))return finish("failed","invalid_request","Derived target is outside the bounded branch admission; pass a bounded explicit target.");data.targetBranch=target;data.targetSource="parent-read";resolved=true;break;}
   if(!resolved)return finish("failed","observation_failed","Parent read did not yield an admitted parent; pass an explicit target.");
  }
  if(source.branch===parseSwitchTarget(data.targetBranch!)!.branch)return finish("failed","invalid_request","Refusing a same-branch closeout within the admitted workspace scope.");
  const cardLine=submitted.cardRef?.trim()?`\n\n${submitted.cardRef.trim()}`:"";data.checkinMessage=submitted.message?.trim()?submitted.message.trim():`Merge ${data.sourceBranch} into ${data.targetBranch}${cardLine}`;
  // Existing checkin owner rejects control/newline text. Never discover that only after target mutation.
  if(!checkinSafeValue(data.checkinMessage)||[data.checkinMessage,cwd].reduce((n,s)=>n+s.length,0)>16384||Buffer.byteLength(JSON.stringify([data.checkinMessage,cwd]),"utf8")>32768)return finish("failed","invalid_request","Derived checkin message is outside the existing child admission; supply an admitted explicit message before any target mutation.");
  const before=await pending("pending-before");if(!before)return finish("failed");data.targetVerification=compareSwitchTarget(start,data.targetBranch!);
  if(data.requested.preflight)return finish("preflight");
  if(data.targetVerification==="unverified"&&before.totalPending>0)return finish("blocked","policy_blocked","Pending changes block switching under the unchanged cancel policy; no target mutation permitted.");
  stage="switch";childEntered=true;const switched=await assembleSwitchReceipt({branch:data.targetBranch!,pendingChanges:"cancel",workdir:cwd});push({name:"switch",kind:"switch",result:switched});childEntered=false;if(!switched.ok)return finish("failed","child_failed");
  if(!await loaded("loaded-after-switch",true))return finish("failed","target_unverified");
  if(data.requested.updateTarget){stage="update";childEntered=true;const updated=await assembleUpdateReceipt({workdir:cwd});push({name:"update",kind:"update",result:updated});childEntered=false;if(!updated.ok)return finish("failed","child_failed");}
  if(!await loaded("loaded-before-merge",true))return finish("failed","target_unverified");
  stage="merge";childEntered=true;const merged=await assembleWorkspaceMergeReceipt("merge",{source:data.sourceBranch!,strategy:data.requested.strategy,workdir:cwd});push({name:"merge",kind:"merge",result:merged});childEntered=false;if(!merged.ok)return finish("failed","child_failed");
  const copiedReady=merged.data.protocol==="apply-add-copied";
  const ready=await read("readiness",copiedReady?[...switchPendingArgv]:["status"]);if(!ready.success||ready.o.stderr!==""||!(copiedReady?!!parseCopiedPending(ready.o.stdout!,cwd):admitCleanStandardStatus(ready.o.stdout!)))return finish("failed","observation_failed","Independent post-merge readiness is outside the admitted profile; no checkin permitted. Prior effects remain possible.");ready.s.admission="admitted";
  if(!await loaded("loaded-before-checkin",true))return finish("failed","target_unverified");
  const checkinArgs={message:data.checkinMessage,includeAll:true,includePrivate:data.requested.includePrivate,workdir:cwd};
  stage="checkin-preflight";childEntered=true;const preview=await assembleCheckinReceipt({...checkinArgs,preflight:true});push({name:"checkin-preflight",kind:"checkin",result:preview});childEntered=false;if(!preview.ok)return finish("failed","child_failed");
  stage="checkin";childEntered=true;const checked=await assembleCheckinReceipt(checkinArgs);push({name:"checkin",kind:"checkin",result:checked});childEntered=false;data.createdChangeset=checked.data.createdChangeset;if(!checked.ok)return finish("failed","child_failed");
  if(!await loaded("loaded-final",true))return finish("failed","target_unverified");
  const final=(data.stages.at(-1)! as Extract<CloseoutStage,{kind:"read"}>).result.branch!;
  if(!data.createdChangeset||data.createdChangeset.branch!==final.branch||data.createdChangeset.repository!==final.repository||data.createdChangeset.server!==final.server)return finish("failed","target_unverified","Observed changeset retained but its branch/repository/server spelling is not the final loaded target. No alias equivalence or target checkin proof inferred.");
  const after=await pending("pending-final");if(!after)return finish("failed");data.pendingAfter=after;return finish("completed");
 }catch{if(childEntered){data.unobservedChild=stage as CloseoutData["unobservedChild"];data.unattemptedStages=data.unattemptedStages.filter(n=>n!==stage);}return finish("failed",stage==="input"?"invalid_request":"producer_failed",stage==="input"?"Use only declared bounded branch selectors, strict closeout controls and admitted checkin text.":"Closeout observation failed; prior effects remain possible. No compensation or automatic replay.");}
}
