import {captureWorkspaceMergeCommand,emptyWorkspaceMergeAttempt} from "../execution/workspace-merge-command";
import {safeBranchDeleteText} from "../domain/branch-delete-contract";
export const validObjectDeleteText=safeBranchDeleteText;
export type ObjectDeleteAction="shelveset-delete"|"code-review-delete";
export type ObjectDeleteRequest={operands:string[];repository:string|null;workdir:string;preflight:boolean;format:"text"|"json"};
export type ObjectDeleteData={requested:ObjectDeleteRequest|null;intendedArgv:string[];attempt:ReturnType<typeof emptyWorkspaceMergeAttempt>;capture:Awaited<ReturnType<typeof captureWorkspaceMergeCommand>>["capture"]|null;observedDeletedObjects:null;observedRepositoryIdentity:null;scope:"requested-only";rollback:"not-proven";effect:"not-attempted"|"not-proven"|"uncertain"};
export type ObjectDeleteReceipt={schemaVersion:1;action:ObjectDeleteAction;provenance:{source:"plastic";producer:"@aefree/pi-plastic";contentTrust:"external"};completeness:{capture:"complete"|"incomplete"|"unknown";projection:true};data:ObjectDeleteData}&({ok:true;outcome:"preflight"|"command-completed"}|{ok:false;outcome:"failed"|"uncertain";error:{code:"invalid_request"|"launch_failed"|"aborted"|"uncertain"|"producer_failed";message:string}});
export const objectDeletePrefix=(a:ObjectDeleteAction)=>a==="shelveset-delete"?["shelveset","delete"]:["codereview","-d"];
export const objectDeleteArgv=(a:ObjectDeleteAction,r:ObjectDeleteRequest)=>[...objectDeletePrefix(a),...r.operands,...(r.repository===null?[]:[`--repository=${r.repository}`])];
export function validObjectDeleteOperands(a:ObjectDeleteAction,v:unknown):v is string[]{if(!Array.isArray(v)||v.length<1||v.length>(a==="shelveset-delete"?1:256))return false;let bytes=0;for(let i=0;i<v.length;i++){const s=v[i];if(!safeBranchDeleteText(s)||s.trimStart().startsWith("-"))return false;bytes+=Buffer.byteLength(s,"utf8");if(bytes>32768)return false;}return true;}
export function emptyObjectDeleteData(action:ObjectDeleteAction):ObjectDeleteData{return {requested:null,intendedArgv:objectDeletePrefix(action),attempt:emptyWorkspaceMergeAttempt(),capture:null,observedDeletedObjects:null,observedRepositoryIdentity:null,scope:"requested-only",rollback:"not-proven",effect:"not-attempted"};}
function header(action:ObjectDeleteAction,data:ObjectDeleteData){return {schemaVersion:1 as const,action,provenance:{source:"plastic" as const,producer:"@aefree/pi-plastic" as const,contentTrust:"external" as const},completeness:{capture:data.capture?data.capture.complete?"complete" as const:"incomplete" as const:"unknown" as const,projection:true as const},data};}
export function objectDeleteFailure(action:ObjectDeleteAction,data:ObjectDeleteData,code:Extract<ObjectDeleteReceipt,{ok:false}>["error"]["code"],message:string):ObjectDeleteReceipt{return {...header(action,data),ok:false,outcome:data.effect==="uncertain"?"uncertain":"failed",error:{code,message}};}
export async function assembleObjectDeleteReceipt(action:ObjectDeleteAction,args:unknown):Promise<ObjectDeleteReceipt>{const data=emptyObjectDeleteData(action);let entered=false;try{
 if(!args||typeof args!=="object"||Array.isArray(args)||Object.keys(args).some(k=>!(action==="shelveset-delete"?["shelveset","preflight","format","workdir"]:["ids","repository","preflight","format","workdir"]).includes(k)))return objectDeleteFailure(action,data,"invalid_request","Use only declared bounded object-delete controls.");
 const i={...args} as Record<string,unknown>,operands=action==="shelveset-delete"?[i.shelveset]:Array.isArray(i.ids)&&i.ids.length<=256?Array.from(i.ids):i.ids,cwd=i.workdir===undefined?process.cwd():i.workdir,repository=i.repository===undefined?null:i.repository,preview=i.preflight===undefined?false:i.preflight,format=i.format===undefined?"text":i.format;
 if(!validObjectDeleteOperands(action,operands)||!safeBranchDeleteText(cwd)||repository!==null&&!safeBranchDeleteText(repository)||Object.hasOwn(i,"repository")&&i.repository===null||typeof preview!=="boolean"||!["text","json"].includes(format as string))return objectDeleteFailure(action,data,"invalid_request","Use bounded exact operands, repository text, strict preview boolean and text/json. Options/stdin are rejected.");
 const r:ObjectDeleteRequest={operands:[...operands],repository:repository as string|null,workdir:cwd,preflight:preview,format:format as "text"|"json"};if(Buffer.byteLength(JSON.stringify(r),"utf8")>32768)return objectDeleteFailure(action,data,"invalid_request","Request exceeds aggregate byte budget.");data.requested=r;data.intendedArgv=objectDeleteArgv(action,r);
 if(preview)return {...header(action,data),ok:true,outcome:"preflight"};entered=true;const o=await captureWorkspaceMergeCommand([...data.intendedArgv],cwd);data.attempt=o.attempt;data.capture=o.capture;if(o.capture.complete&&!o.failed&&o.attempt.state==="started"&&o.attempt.exitCode===0){data.effect="not-proven";return {...header(action,data),ok:true,outcome:"command-completed"};}data.effect=["started","unknown"].includes(data.attempt.state)?"uncertain":"not-attempted";return objectDeleteFailure(action,data,o.attempt.aborted?"aborted":data.effect==="uncertain"?"uncertain":"launch_failed","Object deletion completion is not proven; inspect earlier possible effects before deciding whether to retry.");
 }catch{if(entered){data.attempt={...emptyWorkspaceMergeAttempt(),state:"unknown"};data.capture=null;data.effect="uncertain";}return objectDeleteFailure(action,data,"producer_failed","Object deletion observation failed; no rollback or safe retry is proven.");}}
export function presentObjectDeleteReceipt(dto:ObjectDeleteReceipt):string{if(dto.data.requested?.format==="json")return JSON.stringify(dto);if(!dto.ok)return `${dto.action} ${dto.outcome}: ${dto.error.message} Effects: ${dto.data.effect}.`;if(dto.outcome==="preflight")return `${dto.action} command-only preview (not executed): ${JSON.stringify(dto.data.intendedArgv)}. No existence/readiness analysis.`;return `${dto.action} command completed for ${dto.data.requested!.operands.length} requested operands. Deleted identities, repository scope and rollback remain unverified.`;}
